/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 网约房系统接口文档 - version 1.0
 *
 * 网约房系统接口说明
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.getLoginUserUsingGET': ['GET', '/getLoginUser'],
  'general.doWxLoginUsingPOST': ['POST', '/login/doWxLogin'],
  'general.wxAuthorizeLoginCodeUsingPOST': ['POST', '/login/wxAuthorizeLoginCode'],
  'general.logoutUsingGET': ['GET', '/logout'],
  'general.mLoginUsingPOST': ['POST', '/mlogin'],
  'general.refreshTokenUsingPOST': ['POST', '/refreshToken'],
  'general.sendSmsUsingPOST': ['POST', '/sendSms'],
  'general.sendSmsCheckUsingGET': ['GET', '/sendSmsCheck']
};
